language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  # disable xdebug if available
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  # flags to pass to install
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - composer install $flags

script:
  - ./vendor/bin/phpunit
